# Opérations de base d’un réseau ConvNet

In [1]:
import numpy as np

In [2]:
# Définir image
ni = 9
mi = 9
image = np.random.randint(5, size=(ni,mi))
print(image)

[[1 4 1 0 4 2 2 0 4]
 [4 3 3 4 3 2 4 0 3]
 [0 4 4 0 0 0 2 3 4]
 [0 2 1 3 2 3 2 4 2]
 [3 1 1 1 0 2 2 0 4]
 [2 4 3 2 4 4 3 0 0]
 [4 4 3 0 1 4 2 1 2]
 [2 4 0 1 1 3 2 3 2]
 [2 0 1 2 1 0 3 1 1]]


In [3]:
#Définir filtre
nf = 3
mf = 3
filtre = np.random.randint(5, size=(nf,mf))
print(filtre)

[[4 3 0]
 [0 0 1]
 [1 0 3]]


In [4]:
# Application du filtre
nv_image = np.empty(shape=(ni-nf, mi-mf), dtype=object)
for i in range(ni-nf) :
    nv_image[i] = np.empty(mi-mf, dtype=object)
    for j in range(mi-mf) :
        somme = 0
        for k in range(nf) :
            for l in range(mf) :
                somme += image[i+k, j+l] * filtre[k, l]
        nv_image[i, j] = somme

In [5]:
print(nv_image)

[[31 27 11 14 32 23]
 [32 32 31 37 28 38]
 [19 35 19 10 8 12]
 [18 22 28 34 32 22]
 [31 13 17 20 16 21]
 [25 32 22 34 37 38]]
